### ISSUE TITLE
Validate Model Parameters Defined at Runtime 

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#189]
I recently added an option input file that allows the user to redefine a selection of model parameters at runtime.  Previously, these parameters were defined as global constants and were defined at the time of compilation.  Now that these parameters are exposed to the user, we need to add some logic to ensure that they remain within reasonable bounds.   This logic will go in [`get_parameters()`](https://github.com/UW-Hydro/VIC/blob/develop/drivers/shared/src/get_parameters.c) and will just need to check that each value is inside a plausible range.

**Comment by bartnijssen** [comment]
This is great - having all these hardcoded parameters is one thing that Martyn Clark has been criticizing in a lot of models, so making them accessible in a configuration file is really the way to go. That said, I think we should keep the checking to a minimum, not because we should not do any checking, but because it adds a lot of logic to VIC that needs to be duplicated in all the drivers. It makes more sense to me to write a separate 'configuration checker' in python that will do more extensive checking, since I/O is much more easily handled in python and we can check input files independent of the driver that is used.

So I would just check things like 'signedness' and use wide ranges.

**Comment by jhamman** [comment]
That's basically what I was thinking too.  I'll put a PR together and we can go from there.

**Comment by jhamman** [comment]
closed via #192.
