### ISSUE TITLE
Will VIC 5.0 support parallel computation？

### ISSUE THREAD

**Issue by pengbinpeluo** [UW-Hydro/VIC#191]
I am just wondering whether VIC 5.0 will support some parallel computation options or not...many thanks!

**Comment by bartnijssen** [comment]
Yes - the idea is that there will be different drivers, which will support parallelization in different ways:

* classic - same as now in which time is the most rapidly varying dimension (time before space). Just like the current mode, this means that you can easily implement parallelization by running different grid cells on different nodes or processors. That is already supported, but must be implemented by the user when scripting the runs.

* image - we are currently implementing MPI support for this. It is relatively straightforward, because all VIC grid cells are independent. In the initial implementation, all I/O will happen on the master node. This means that spatial fields will be read on the master node and then scattered (MPI_Scatterv) to the other nodes. Similarly spatial fields will be gather to the master node (MPI_Gatherv) and then written to file. See https://github.com/bartnijssen/VIC/tree/feature/mpi <https://github.com/bartnijssen/VIC/tree/feature/mpi> for an initial implementation. We are in the process of testing this.

**Comment by jhamman** [comment]
Yes.  This work is currently underway.  Would you be interested in contributing to the development or testing the beta version of VIC.5.  

We will only be adding MPI to the image mode driver (time on the outer loop, space on the inner loop).

**Comment by pengbinpeluo** [comment]
Thank you, Bart and Joe for this introduction. If possible, I hope I can make some contribution to VIC 5. Actually some months ago, I once changed the VIC 4.2 from "time before space" to "space before time" mode and add NetCDF forcing, soil parameter file and output options. However, these are conducted only for some personal jobs.

**Comment by bartnijssen** [comment]
Excellent - image mode also does all I/O in NetCDF. If you'd be wiling to help with some testing that would be great!
