### ISSUE TITLE
Model Crashes When OUTPUT_FORCE=TRUE

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#201]
When using `OUTPUT_FORCE = TRUE`, the model crashes with a `segmentation fault: bad access`.

Looking into this a bit deeper, this problem is coming in two locations where access to the `veg_con` structure, isn't protected by a `if (!options.OUTPUT_FORCE) {}` block.  This occurs in two blocks of the `initialize_atmos()` code:

1.  [Assign N_ELEM for veg-dependent forcings](https://github.com/UW-Hydro/VIC/blob/master/src/initialize_atmos.c#L257-L260),
2.  [Albedo, LAI, and Fractional Veg Cover](https://github.com/UW-Hydro/VIC/blob/master/src/initialize_atmos.c#L1424-L1589).

I've already applied a fix locally but this is probably going to mean we release a `hotfix/4.2.b` tag.

**Comment by bartnijssen** [comment]
@jhamman  - I am confused about the tag naming. I though bug fixes were identified by letters (`4.2.a`, `4.2.b`) rather than numbers. I already didn't understand `4.2.1`, but am concerned that this will cause confusion for the `4.X` series. Even if going forward it'll be `<major release>.<minor release>.<bug fix>` then that would be easier from `5.0` going forward (i.e. `5.0.1` is a bug fix for `5.0`). I'd prefer if we retag the `4.2.1` tag as `4.2.a` and call this one `4.2.b`, given that the `4.1.0` to 4.1.2` were essentially minor releases rather than bug fixes.

**Comment by jhamman** [comment]
@bartnijssen - We stopped using the alphabetic bugfix identifier when we went to `4.2.0`.  That discussion was in issue #49.  When the issues was close, I specifically addressed the convention that was used for the `4.2.1` release.

**Comment by bartnijssen** [comment]
I know we had that discussion. After seeing it in practice, I really don't like it because it is misleading within the 4.X universe. For this reason I am making the decision to change it and adopt it from 5.X on instead.
