### ISSUE TITLE
Reworking the VIC users group 

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#208]
A quick summary for context for where we are right now:

- [`vic_users@u.washington.edu`](https://mailman13.u.washington.edu/mailman/listinfo/vic_users) is the VIC users group mailing list 
- It is moderated by @tbohn, @bartnijssen, and myself (@jhamman) here at the University of Washington
- Post routinely bounce because users are not registered correctly with the UW system
- Querying the archive of posts is possible but difficult, requires sign-up/in.

I'm just throwing a few ideas out there for how we could improve the interaction of VIC users through a different system. Some of this is aimed at moving the support of VIC into the public domain.

1.  [Google Groups](https://groups.google.com) : Online Google forums.  Interaction with the forum is through the web (typically) but users can be notified by email.  Supports a number of "Group Types" including email lists, Q & A forums, and collaborative forums.  
2.  [Stack Exchange](http://stackexchange.com/) or Equivalent : This is really a question and answer forum model and would not offer many ways to make group announcements.  It does offer easy searching and querying of previous questions.
3.  [Github Issues](https://github.com/UW-Hydro/VIC/issues) : Perhaps the least attractive option, using the github issues page for VIC would also be a mechanism for Q & A.
4.  [UW listserve](https://mailman13.u.washington.edu/mailman/listinfo/vic_users) : This is the status quo / no change option.

There may be other options and the point of me raising this issue is to start the discussion and voice my mild displeasure with the current users group setup.

**Comment by bartnijssen** [comment]
My preference for now would be the status quo. There is not really enough activity at the moment that motivates me to change this. Maybe traffic is low because it is clunky, but so be it. 90% of the questions are answered in the VIC documentation already.

My least preferred option is github, which I want to reserve for discussion about code and don't want to clutter with questions on where to find the VIC executable. Google groups always seems rather clunky.

So my preference is to maintain the status quo. If another member of the VIC community wants to set up a bigger forum that is fine, but we're already doing enough.

**Comment by tbohn** [comment]
I'm OK with whatever option you end up choosing.  I guess the bouncing
emails are a problem that needs to be solved - we'd need something that is
easy for non-members to either join or post to without being a member.

Ted

**Comment by jhamman** [comment]
Closing.  Will include a note about gitter in VIC 5 release email.
