### ISSUE TITLE
Why are we passing global_param into vic_run?

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#230]
`global_param` is an `extern` but is also passed as an argument. @bartnijssen - was this intentional?

see this line: https://github.com/UW-Hydro/VIC/blob/develop/vic/drivers/image/src/vic_image_run.c#L54

**Comment by bartnijssen** [comment]
The link does not work. I get a 404 error

**Comment by bartnijssen** [comment]
I don't quite understand the questions. When I look at `vic_run()`, then `global_param_struct *gp,` is passed `extern parameters_struct param;` is `extern`. This was mostly to stay consistent with VIC classic.

**Comment by jhamman** [comment]
Yes, I think our question was why pass the structure if it is a global. If I remember right, we are choosing not to use `global_param` as a global in `vic_run`? 

cc: @wietsefranssen

**Comment by bartnijssen** [comment]
Right - we were trying to limit the number of globals (defined as extern) in `vic_run` to truly separate the driver from the physics. I left 

```C
    extern option_struct     options;
    extern parameters_struct param;
```

since that was easiest and none of the variables in these structures are location-dependent (i.e. same for entire domain). We could also pass these as function arguments, but they are used in a large number of the `vic_run()` functions and it would be a reasonable amount of work to do make sure they get passed to all the other functions.

**Comment by jhamman** [comment]
Okay.  Thanks for the refresher.  I'm going to close this.  If @wietsefranssen has any additional questions, we can reopen the issue.

**Comment by wietsefranssen** [comment]
Hi, I don't have additional questions, Its also all clear for me now.
