### ISSUE TITLE
Some sample global parameter files contain outdated options

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#356]
Global parameter files are found in the following locations:
```
samples/global.param.sample
tests/examples/global*
tests/release/global*
tests/system/global*
```
Many of these contain outdated options like `MEASURE_H`, `STARTHOUR`, `TIME_STEP`, `PLAPSE`, etc. that have been removed in 5.0.  We need to update these to work for 5.0.

**Comment by jhamman** [comment]
I will update all the `tests/*` global parameter files when I start working on the test modules again.  This probably wont happen until February but its on my list and I know these have become out of date.

As for the sample, we should rename `global.param.sample` to `global.param.sample.classic.txt` and also include one for the image driver (`global.param.sample.image.txt`).  @tbohn - since you seem to already be on that track, do you want to take on that task?

**Comment by tbohn** [comment]
Sure, I can take that on.

**Comment by tbohn** [comment]
Some differences between classic and image versions of the global.param.sample file:
* VEGLIB_VEGCOVER and VEGPARAM_LAI/VEGCOVER/ALBEDO are disabled in image mode and should be excluded from the sample file
