### ISSUE TITLE
ENH: Isolate MPI code in Image Driver

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#375]
@tbohn recently asked if it is possible to compile and run the VIC image driver without MPI.  This is currently not possible but sand-boxing the MPI code should be possible.

**Comment by bartnijssen** [comment]
Yes agreed - although for any larger scale applications the use of MPI would be a must-have, since "poor man's parallelization" a la `vic_classic` is no longer possible. Keep in mind that you can run with mpi on a single processor, so this seems to be mostly a compilation issue and using MPI is not that onerous on most systems (not sure about windows),

So I would leave this as a low priority for now (`someday` as a milestone seems about right).

**Comment by tbohn** [comment]
This is fine with me too as I was simply asking to find out what my options were - at the time, my machine didn't have mpi.

**Comment by bartnijssen** [comment]
Actually - maybe we leave this as-is and instead focus on getting VIC to compile within a container architecture. That would require users to install Docker or something like it, but it would take away the need for compilation on different systems.

So my vote for now would be to mark this as "won't fix" and instead focus on issue #350.

**Comment by jhamman** [comment]
Okay, closing then for now.  We can reopen if someone is interested in the future.
