### ISSUE TITLE
TESTING: Miscellaneous issues related to system test

### ISSUE THREAD

**Issue by yixinmao** [UW-Hydro/VIC#515]
Currently system test run has a couple of miscellaneous issues:
- It is right now not run on travis - need to add system config file path to travis build for both drivers
- Now for domain-checking test for image driver, the domain file is set to directly been read from sample data set - need to change the domain file path in `system.cfg`
- Remove the domain file under `tests/examples` directory - no longer need it

**Comment by bartnijssen** [comment]
@yixinmao , @dgergel : Can you update the status of this and assign a milestone? Does this need to be resolved before 5.0?

**Comment by yixinmao** [comment]
@bartnijssen : it seems that the first two bullet points are already resolved. The last point just needs an unused file to be removed from the repo (I can do this)

**Comment by bartnijssen** [comment]
@yixinmao : I just reassigned you to this so you can take care of it. 

As a side note: Please do not use "miscellaneous issues" as the title for an issue, since the issue are meant to be specific. So if there is more than one, just assign separate issues. In addition, make the title of the issue as specific as possible. When scrolling through a long list of issues, a title such as this one "Miscellaneous issues related to system test" is too vague.

**Comment by yixinmao** [comment]
Issues resolved via PR #491 (bullet point 1), #517 (point 2) and #576 (point 3).
