### ISSUE TITLE
DOC: FAQ on getting 4.2 behavior in 5.0.

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#613]
Add entry to FAQ that describes how to get exact 4.2 behavior out of VIC.5 classic driver.

What options did we need to change for the science testing?

One that came by default in your tests is `RUNOFF_STEPS_PER_DAY = 24` but we should say that in the FAQ explicitly. 

cc @yixinmao and @dgergel

**Comment by yixinmao** [comment]
@jhamman what do you want this FAQ exactly to be? Should we just point to the science test global file example (and add some comments about those default or changed global options in the example global files), or address this question more generically by listing out all global options that need to be changed (would there be a lot?)?

**Comment by dgergel** [comment]
The way I understand it, since we want VIC 5 to behave like 4.2, the key difference is the value of the constants that have changed. Meaning that if users use the `vic_parameters_42_compat.txt` that we have in the `/tests/science` directory and specify this in the global parameter file, the classic driver will be equivalent to VIC 4.2. (in addition to the 'RUNOFF_STEPS_PER_DAY` difference that @jhamman mentioned above).

**Comment by dgergel** [comment]
I'll have a PR on this momentarily.

**Comment by yixinmao** [comment]
@dgergel Thanks Diana! Yeah you are right - I think there might be some additional global parameters we need to take care of as well - for example, VIC4.2 actually gets wind measurement height over bare soil from a hardcoded header file, versus VIC5 classic gets it from the global parameter file.

**Comment by bartnijssen** [comment]
The FAQ needs to be complete and explicit about all the changes we needed to make to get the two runs to match. Don't just send people to some global file that may change in future code changes.

**Comment by dgergel** [comment]
@bartnijssen yes, for sure. @yixinmao thanks, I'd forgotten about that. Are there additional options that you can think of?

**Comment by jhamman** [comment]
closed via #622
