### ISSUE TITLE
 bad revision 'HEAD'

### ISSUE THREAD

**Issue by TUFCC** [UW-Hydro/VIC#660]
latest version always reported a variety of errors. After many of my debugging, now there is the problem, what is the reason?
![qq 20161230123027](https://cloud.githubusercontent.com/assets/16103058/21559693/d778554a-ce8b-11e6-84d1-2001faacb548.png)

**Comment by bartnijssen** [comment]
@TUFCC : If you already cloned the repo then you should not need reinitialize it since the repo already exists. We cannot provide support for errors you are getting on cygwin. If you find a solution you are more then welcome to post it here for others, but we will not spend time to fix or diagnose this, since it passes all our build checks.
