### ISSUE TITLE
Compile error while running make command in image driver

### ISSUE THREAD

**Issue by arunima07** [UW-Hydro/VIC#664]
Open MPI Version : 2.0.1

Netcdf : nc-config --all
This netCDF 4.3.3.1 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/home/arunima/miniconda2/include 
  --libs      -> -L/home/arunima/miniconda2/lib -lnetcdf

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no

  --prefix    -> /home/arunima/miniconda2
  --includedir-> /home/arunima/miniconda2/include
  --version   -> netCDF 4.3.3.1
[image_driver_make_logs.txt](https://github.com/UW-Hydro/VIC/files/701407/image_driver_make_logs.txt)

**Comment by jhamman** [comment]
your compiler is not finding the hdf5 library. I see you are using the anaconda netcdf distribution. I would think this is going to be a problem since the netcdf binary is not really intended for use like this. Try using a another build of netcdf/hdf (on mac try macports or homebrew, on linux try your distributions package manager).

**Comment by arunima07** [comment]
Thanks. Issue is solved.
