### ISSUE TITLE
 Segmentation faults when the lake model is running

### ISSUE THREAD

**Issue by gina-tsarouchi** [UW-Hydro/VIC#754]
Version: VIC 5.0.1 (image driver)
Description: When running the Lake model, after the initialization is complete, the below segmentation fault occurs:

```
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: 0x7ffe66456000
[ 0] /lib64/libpthread.so.0(+0xf370)[0x7f4e53b1b370]
[ 1] ./vic_image.exe[0x41b160]
[ 2] ./vic_image.exe[0x422818]
[ 3] ./vic_image.exe[0x408ccf]
[ 4] ./vic_image.exe[0x48989b]
[ 5] ./vic_image.exe[0x449810]
[ 6] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f4e5376cb35]
[ 7] ./vic_image.exe[0x402c89]
*** End of error message ***
```

**Comment by jhamman** [comment]
@gina-tsarouchi - thanks for the report. IIRC, we have not finished testing the lake model in VIC.5 yet. @tbohn can probably give us a better idea of where things stand.

**Comment by tbohn** [comment]
I'm afraid I can't shed much light at the moment.  I think the lake model might work in the classic driver.  I think Joe is right, that the implementation of the lake model in the image driver is simply incomplete.

I don't have much time to spend looking into this, to see what needs to happen.  It's got to be confined to the driver code, though, since the lake physics are of course all in the vic_run section of the code.  So presumably it wouldn't take a ton of work to get the lake model working.

Perhaps part of the reason it wasn't implemented in image mode was that the lake model has always been a weird sub-tile of the veg tiles, and does not work with elevation bands (even in classic driver).  This whole structure could use an overhaul.

**Comment by tbohn** [comment]
It looks like the above changes are necessary, but not sufficient.  A similar change needs to be made a few lines later, in the call to `put_data()`. I'm working on testing this but also fixing up a few other minor issues with lake-related code. Stay tuned.

**Comment by itzetoile** [comment]
Thank you Ted, Please keep me posted if you find other issues for lakes.

**Comment by itzetoile** [comment]
Hi,

We have come across a couple of other bugs for the lake option. We are currently fixing them, we will let you know when these are done.

**Comment by tbohn** [comment]
Sure, thanks for letting us know. Please make a new issue for those.

**Comment by tbohn** [comment]
Hi @itzetoile, I've also been testing the lake model and have found some bugs. I'm not finished fixing them. But so far I have found a problem with the call to `generate_default_lake_state()`, which I've fixed. I will add that fix to my existing PR #812. But I'm now finding other suspicious behavior. Before I continue further, maybe it would be a good idea for us to compare what we have found? That could speed up our investigation and fixing...

**Comment by tbohn** [comment]
I have created a PR (#826) that fixes the various bugs I've found so far. These include validating lake parameters, generating the default lake state (using `depth_in` from the lake parameters), and writing lake variables to the state file. I might add more fixes to that PR as I find them.

**Comment by itzetoile** [comment]
Hi, I am checking your fixes and comparing them to ours, it looks like you have found most of what we also found, except for a few lines that I will add. However, before I add them, I would like to ask you what is the exact difference between Nlakenode and Nlakebasenode. I do not really get it and I saw that now they are separated and inlcued in your fixes. Thanks

**Comment by itzetoile** [comment]
One additional thing: IF NLAKENODES is removed from the code and replaced by Nlakenode and Nlakebasenode, it needs to be changed as well in vic_restore.c. I did not see this change in your fixes, but I cannot access them anymore as checks appeard now as failed for fix/fix lake bugs

**Comment by tbohn** [comment]
Thanks for catching that, @itzetoile .  I originally made my changes in a directory outside of git, and then copied all of my edited source code back to my git directory. Except I forgot to copy `vic_restore.c`. I've fixed that and pushed to my PR.

To answer your question:
- `Nlakebasnode` is the length of the `lake_node` dimension in the parameter file (assuming you're using image mode).  This must be >= the maximum value of `numnod` found anywhere in the file. And `numnod` is the number of points in the lake depth-area relationship in a given grid cell. It is static. It simply helps define the lake basin shape. And, in the code, the run-time value of `Nlakebasnode` is limited by the pre-compile definition of `MAX_LAKE_BASIN_NODES`.
- `Nlakenode` is the length of the `lake_node` dimension in the state files (again, assuming you're using image mode).  This must be >= the maximum value of of `activenod` found anywhere in the file. And `activenod` is the number of lake water layers in a given grid cell. It is dynamic, because lakes change volume. VIC is constantly recomputing the boundaries of lake water layers, and their accompanying surface areas and volumes; these rarely match the points in the depth-area relationship. As the lake shrinks, layers become thinner, and eventually they become too thin to use, so VIC starts reducing activenod to maintain a certain minimum layer thickness. And, in the code, the run-time value of `Nlakenode` is limited by the pre-compile definition of `MAX_LAKE_NODES`.

There is no good reason why the maximum number of lake water layers must match the maximum number of points in the depth-area relationship. If a user wants to have more lake layers, for more accuracy, or fewer maximum layers to save memory and increase speed, it should be possible to make that change in the global parameter file without having to worry about whether the lake parameters need to be changed.

There were places in the code where the value of `Nlakenode` was being set equal to the length of the `lake_node` dimension in the parameter file (which pertains to depth-area relationships). Then, elsewhere in the code, this value of `Nlakenode` was being compared to the `lake_node` dimension length in the state file, and if they were different, the code would exit. I think it is necessary to have this type of validation, so I didn't want to remove it. I just made the validation more correct by separating the two types of `lake_node` dimensions.

This isn't so much of an issue in the classic driver, since the parameter and state files do not need to specify a dimension length for these things. Still, limiting them both by the `MAX_LAKE_NODES` limit in the code was still technically an incorrect linking of the two different concepts.

**Comment by itzetoile** [comment]
Thank you Ted, this is very helpful. The only bug I could add to your fixes is in share_image/src/vic_store.c. I ma not sure if it is worth to open a new case for it. 

        // soil node temperatures: lake_var.energy.T[nidx]
        nc_var = &(nc_state_file.nc_vars[STATE_LAKE_SOIL_NODE_TEMP]);
        for (j = 0; j < options.Nnode; j++) {
            d3start[0] = j;
            for (i = 0; i < local_domain.ncells_active; i++) {
// CB-092018 bugfix: copy-paste error
            dvar[i] = (double) all_vars[i].lake_var.energy.T[j];
//                dvar[i] = (double) all_vars[i].lake_var.soil.layer[j].moist;
            }



just one line, I am not sure if I should push it to the git repository. I have not jet updated your new fixes to my repository, and I have a few extra lines that are not nee

**Comment by tbohn** [comment]
I've opened an issue for this (#841).

I'm happy to make a PR for this change - it will take me 5 minutes. I think
it's good to fix these bugs (with pull requests) as soon as we find them,
so that other users can benefit from them.

**Comment by tbohn** [comment]
OK, now I've opened a PR for this, #842.
