### ISSUE TITLE
vic daily steps ?

### ISSUE THREAD

**Issue by li984096131** [UW-Hydro/VIC#804]
#### Bug Reports

- Version of VIC :5.0.1 Feb1,2017
- gcc and g++
- linux ubuntu 16.4?

I want to run vic 1step per day
so I set the MODEL_STEPS_PER_DAY=1, SNOW_STEPS_PER_DAY=1, RUNOFF_STEPS_PER_DAY=1, 
FULL_ENERGY=FALSE, FROZEN_SOIL=FALSE, and FORCE_STEPS_PER_DAY=1.
but when I run vic,he tell me "the specified number of snow model steps per day (1)< the minimum number of subdaily steps per day (4). make sure that the global file defines SNOW_STEPS_PER_DAY of at least (4)."
my question:
1.what is the"subdaily steps per day" ? can I set it to (1) ?
2.how can I run vic for 1 step per day? how to set the parameters?

**Comment by jhamman** [comment]
VIC 5 requires that you supply forcings at a maximum timestep of 6 hours (e.g. MODEL_STEPS_PER_DAY=4). This is specified in https://vic.readthedocs.io/en/master/Documentation/Drivers/Classic/ForcingData/.

**Comment by li984096131** [comment]
thank you very much    !
if I use vic 4 ,I will set 1step per day?

**Comment by pyested** [comment]
This is not totally clear in the documentation. The description for MODEL_STEPS_PER_DAY says that it "should be > 4 for FULL_ENERGY=TRUE or FROZEN_SOIL=TRUE" (https://vic.readthedocs.io/en/master/Documentation/Drivers/Classic/GlobalParam/). However, when this is not the case and VIC is run in "water balance mode" (FULL_ENERGY=FALSE) , it is still not possible to set 1 step per day and use daily forcings. 

This is an important difference between VIC 4 and VIC 5. It is not straightforward to migrate from one version to the other if you have always work with daily forcings. You will need to carry out the time disaggregation with MetSim beforehand, for example.

I would suggest a clearer description for MODEL_STEPS_PER_DAY so the user knows it since the beginning. Or even mentioning this in https://vic.readthedocs.io/en/master/Documentation/Drivers/Classic/ForcingData/

**Comment by li984096131** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件。十分感谢。

**Comment by jhamman** [comment]
@pyested - if you're up for updating the documentation as you suggest, we'd be happy to take a look.
